# Generated by Django 3.2.16 on 2022-11-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direct.student', verbose_name='Студенты'),
        ),
    ]
