# Generated by Django 3.2.16 on 2022-11-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_studentgroup_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
    ]
