# Generated by Django 3.2.16 on 2022-11-06 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0003_remove_studentgroup_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direct.studentgroup', verbose_name='Группа, в которую зачислен'),
        ),
    ]
